version: '3'
networks:
  dem:
services: 
  rates_db:
    image: postgres:13.5
    restart: always
    env_file:
      - ./db/.env_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/rates.sql:/docker-entrypoint-initdb.d/rates.sql
    networks:
      - dem

  app:
    restart: always
    build:
      context: ./rates
      dockerfile: Dockerfile
    volumes:
      - .:/rates
    depends_on:
      - rates_db
    networks:
      - dem
    ports:
      - '5000:5000'
    env_file:
      - ./rates/.env_flask
    command: gunicorn -b 0.0.0.0:5000 wsgi