version: '3'
networks:
  dem:
services: 
  rates_db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rates
    ports:
      - "5432:5432"
    volumes:
      - ./db/rates.sql:/docker-entrypoint-initdb.d/rates.sql
    networks:
      - dem

  app:
    restart: always
    build:
      context: ./rates
      dockerfile: Dockerfile
    volumes:
      - .:/rates
    depends_on:
      - rates_db
    networks:
      - dem
    ports:
      - '5000:5000'
    environment:
      - PGPASSWORD=postgres
      - PGHOST=rates_db
      - PGUSER=postgres
      - PGDATABASE=rates
    command: gunicorn -b 0.0.0.0:5000 wsgi